services:
  vmselect-2:
    container_name: vmselect-2
    image: victoriametrics/vmselect
    depends_on:
      - vmselect-1
    command:
      - '--storageNode=vmselect-1:8401'
      - '--clusternativeListenAddr=:8401'
    ports:
      - "8482:8481"
