services:
  vminsert-1:
    container_name: vminsert-1
    image: victoriametrics/vminsert
    depends_on:
      - "vmstorage-1"
    command:
      - '--storageNode=vmstorage-1:8400'
    ports:
      - "8480:8480"
    restart: always
